export const homeObjOne = {
    lightBg: false,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: 'Get Started',
    description: 'We help shape the tech world using state-of-the-art business techniques',
    headline: 'Hire the best people',
    lightText: true,
    topLine: 'Columbus Marketing Agency',
    img: require('../../images/drew-blue.svg').default,
    alt: 'Image',
    start: '',
};